name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la # permet de voir sur le fit ne récupère pas les fichiers du repo

      #installation des librairies
      - run: pip install streamlit
      - run: pip install -U Jinja2
      - run: pip install pytest
      - run: pip install joblib
      - run: pip install sklearn
      - run: npm install cypress

      #lancement des tests unitaires
      - run: pytest test_modelprix.py

      #lancement du test fonctionnel
      - run: streamlit run model_dashboard.py &
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - uses: actions/upload-artifact@v3
        with:
          name: video_cypresstestfonc
          path: /home/runner/work/ynov_projet1/ynov_projet1/cypress/videos/todo.cy.js.mp4